
import { 
  Card, 
  CardContent, 
  CardHeader, 
  CardTitle,
  CardDescription 
} from "@/components/ui/card";
import { 
  BarChart,
  Bar,
  PieChart, 
  Pie, 
  Tooltip, 
  Legend, 
  Cell, 
  ResponsiveContainer,
  XAxis,
  YAxis,
  CartesianGrid
} from "recharts";
import { 
  ChartContainer, 
  ChartTooltip 
} from "@/components/ui/chart";
import { Database, TrendingUp } from "lucide-react";

interface MerchantsTabProps {
  merchantData: {
    name: string;
    value: number;
    color: string;
  }[];
  revenueByMerchant: {
    name: string;
    revenue: number;
  }[];
}

const MerchantsTab = ({ merchantData, revenueByMerchant }: MerchantsTabProps) => {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Database className="h-5 w-5 text-muted-foreground" />
            Merchant Distribution
          </CardTitle>
          <CardDescription>
            Breakdown of merchant status
          </CardDescription>
        </CardHeader>
        <CardContent className="h-[300px]">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={merchantData}
                cx="50%"
                cy="50%"
                labelLine={true}
                outerRadius={80}
                fill="#8884d8"
                dataKey="value"
                label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
              >
                {merchantData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-muted-foreground" />
            Top Merchants by Revenue
          </CardTitle>
          <CardDescription>
            Revenue generated by top merchants
          </CardDescription>
        </CardHeader>
        <CardContent className="h-[300px]">
          <ChartContainer
            config={{
              revenue: { color: "#f59e0b" }
            }}
          >
            <BarChart 
              layout="vertical" 
              data={revenueByMerchant}
              margin={{ top: 20, right: 30, left: 70, bottom: 20 }}
            >
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis type="number" />
              <YAxis dataKey="name" type="category" width={80} />
              <ChartTooltip />
              <Legend />
              <Bar dataKey="revenue" fill="var(--color-revenue)" name="Revenue ($)" />
            </BarChart>
          </ChartContainer>
        </CardContent>
      </Card>
    </div>
  );
};

export default MerchantsTab;
